### ISSUE TITLE
Filter using custom Phosphor image assets

### ISSUE THREAD

**Issue by PSingletary** [FiniteSingularity/obs-retro-effects#13]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Since the filter effects break down an image to "Phosphors" establish a standard length so Matrix Rain or Hacker effects could use custom emotes and images. Imagine a hacker effect made of channel emotes, or the Matrix effect of channel emotes raining down.

**Describe alternatives you've considered**
um didn't not think of an alternative since I don't think anything is like this

**Additional context**
This could potentially be a locally run replacement for Kappagen emote effects

**Comment by PSingletary** [comment]
yes, the matrix rain filter

**Comment by FiniteSingularity** [comment]
So this should be pretty easy to make work.  I'll add a "manual font" button (named better) that allows the user to specify an image.  The image will be a row of the different "characters" (or logos, or whatever) to be used.  The second input the user will need to provide is the number of characters contained in the file.  When the image is assembled, the user will just need to make sure they make the characters evenly spaced.  That way it can all be easily calculated.

As the plugin stands now, the characters to be drawn are all greyscale, and the user provides the "fill" color.  We could also offer the option to use colors from the file (For colored emotes/images/characters/whatever).

**Comment by FiniteSingularity** [comment]
Just realized this was done long ago..  Custom fonts/images have been available in Matrix Rain for a long time.
