### ISSUE TITLE
[BUG] - Different Filters not working on macos

### ISSUE THREAD

**Issue by pr0pz** [FiniteSingularity/obs-retro-effects#21]
**Describe the bug**
Some of the default filters don't work at all with macos.
- CRT
- Dither
- Matrix Rain (already described [here](https://github.com/FiniteSingularity/obs-retro-effects/issues/18))

**To Reproduce**
1. Add the Retro Effects filter to a media/webcam source
2. Choose of the mentioned effects
3. Nothing happens

**Environment**
 - OS/Version: MacOS 14.4.1 (Sonoma) - M1 chip
 - OBS Version: 30.1.2
 - Retro Effects Version: 0.0.8a

**Comment by FiniteSingularity** [comment]
Thank you for the report, and specifically the list of which filters are not yet working.

In terms of a timeline- Matrix Rain and Dither should be relatively straightforward to get working.  The CRT filter on the other hand is a bit more tricky, and so it may take a bit longer.

**Comment by FiniteSingularity** [comment]
Fixed with PR #27
