### ISSUE TITLE
[BUG] - CRT filter makes a hole thing glitch to the center of the screen

### ISSUE THREAD

**Issue by decors1** [FiniteSingularity/obs-retro-effects#23]
**Describe the bug**
CRT filter makes a hole thing glitch to the center of the screen.
Looks like "Barrel Distortion" causes this trouble.
And the combination with "stroke"(especialy inner) this becomes noticeable.
Basically if you change the stroke order and you can avoid this glitch. At least it's not noticeable.
But with tons of filters may this causes a trouble at some point.

**To Reproduce**
1. Create Color Source with Black. (what ever sources but just easier to see the glitch)
2. Add a Retro Effects with CRT on it.
3. Make "Barrel Distortion" to like 0.
4. Add "Stroke" as inner on it. And you'll see tiny white dot.
5. Adjust "Barrel Distortion" value and that will change the behavior.

![image](https://github.com/FiniteSingularity/obs-retro-effects/assets/68762826/579bfa22-499b-494c-bf6c-3cfae18cdc58)

**Environment**
 - OS/Version: Windows 11
 - OBS Version: 30.1.2 (64bits)
 - Retro Effects: 0.0.8a

**GPU**
 - GPU make/model [RTX 4070]
 - GPU VRAM [12Gb]

**Comment by FiniteSingularity** [comment]
Hi @decors1, thank you for the bug report.  I'll take a look into this soon, and figure out what is going on.

**Comment by decors1** [comment]
#36 fixed the issue. 👍
Thx!
