### ISSUE TITLE
[BUG] "Matrix Rain" bloom effect is not updating.

### ISSUE THREAD

**Issue by decors1** [FiniteSingularity/obs-retro-effects#32]
[Describe the bug]

When you start OBS and Matrix Rain bloom effect won't get updated.
This also happens even while runing OBS sometime.
Onece you update some of Retro Effect settings and it'll start blooming again.

Looks like "Bloom Radius" is not updating correct.
(the behavior looks same with "Bloom Radius" = 0)

This issue started occuring from version 0.0.9a. It also occurs in version 0.0.10a too.
(or maybe I just didn't notice in 0.08a?)

[To Reproduce]

(Tested on Clean Installed OBS)
1. add "Color Source"
2. add "Retoro Effects". default is fine.
3. restart OBS
4. you'll see bloom effect is not applied. (same as "Bloom Radius = 0")
5. onece you change some of "Retro Effects" settings and It'll fix the issue.

[Environment]

OS/Version: Windows 11
OBS Version: 30.1.2 (64bits)
Retro Effects: 0.0.9a / 10a

[GPU]

GPU make/model [RTX 4070]
GPU VRAM [12Gb]
![image](https://github.com/FiniteSingularity/obs-retro-effects/assets/68762826/ef9d1b50-5361-445a-8c49-793241b0f98d)

**Comment by FiniteSingularity** [comment]
Thank you for the detailed bug report.  It turns out it is not just the bloom value, but the color, scale, etc.. that are not being reloaded properly. Looking into it now.

**Comment by FiniteSingularity** [comment]
Hi @decors1,

I think I've fixed this with PR #34 .  Can you please try the build in the artifacts at the bottom of this page: https://github.com/FiniteSingularity/obs-retro-effects/actions/runs/9243768210 and let me know if it fixes the issue for you?

**Comment by decors1** [comment]
#34 soleved Matrix Rain Issues I believe. At least bloom thing is now get fixed.At least bloom thing is now get fixed.
